### ISSUE TITLE
[Refactor] 플레이어 관련 코드 리팩토링

### ISSUE THREAD

**Issue by lees5402** [KIA-PROGRAMMING-38/Hollow-Knight#28]
# 설명
- Transform과 관련된 내용은 PlayerController로 구현
- Transform에 종속되지 않은 것들은 State로 구현
- ObjectPooling 삭제 및 이펙트 플레이어에서 단일처리
- PlayerController의 Update 함수에서 입력값에 의한 애니메이션 처리

**Comment by ChoiSeonMun** [comment]
- Animator의 Parameter를 입력에 따른 행동과 대응되게 구성
  - Ex. X키를 누르면 Attack이라고 할 때, Animator의 Parameter도 Attack을 만듦
- 입력값을 저장해두는 PlayerInput 컴포넌트 생성하여 모듈화
- PlayerController는 입력값에 따른 Animator Parameter 업데이트.
- 각 StateMachineBehaviour에는 애니메이션과 종속되는 동작 구현.
  - 독립되는 동작(Ex. 위치 이동)은 PlayerController 혹은 다른 컴포넌트로 모듈화
